apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: fits
  name: fits
spec:
  ports:
  - name: "62005"
    port: 62005
    targetPort: 2113
  selector:
    io.kompose.service: fits
status:
  loadBalancer: {}
